- name: Install the latest version of nginx
  yum:
    name: nginx
    state: latest

- name: Download Packages
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /usr/share/nginx/html
    EXTRACT_DIR: /usr/share/nginx

- name: Copy Extract directory
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy Roboshop config
  copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start Nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes
