- name: Install Erlang
  yum:
    name: https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
    state: present

- name: Download YLM Repo
  shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install Rabbitmq
  yum:
    name: rabbitmq-server
    state: present

- name: Start Rabbitmq
  systemd:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Configure RabbitMQ User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: ["administrator"]
